services:
  keyfile-setup:
    image: mongodb/mongodb-community-server:8.0.21-ubi8-slim
    container_name: keyfile_setup
    user: root
    command: >
      bash -c "if [ ! -f /opt/keyfile/mongo-keyfile ]; then
        head -c 756 /dev/urandom | base64 > /opt/keyfile/mongo-keyfile;
      fi &&
      chown mongod:mongod /opt/keyfile/mongo-keyfile &&
      chmod 400 /opt/keyfile/mongo-keyfile"
    volumes:
      - mongo_key_vol:/opt/keyfile

  mongodb:
    image: mongodb/mongodb-community-server:8.0.21-ubi8-slim
    container_name: articles_mongodb
    depends_on:
      keyfile-setup:
        condition: service_completed_successfully
    restart: always
    command: ["--replSet", "rs0", "--keyFile", "/opt/keyfile/mongo-keyfile"]
    ports:
      - "9003:27017"
    environment:
      MONGO_DB: ${MONGO_DB}
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_ROOT}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_USER: ${MONGO_USER}
      MONGO_USER_PASS: ${MONGO_USER_PASS}
    healthcheck:
      test: mongosh 'mongodb://${MONGO_ROOT}:${MONGO_ROOT_PASS}@127.0.0.1:27017/?authSource=${MONGO_ROOT}' --eval "db.adminCommand('ping')" --quiet
      interval: 10s
      timeout: 5s
      start_period: 15s
      retries: 5
    volumes:
      - mongodb_data:/data/db
      - mongo_key_vol:/opt/keyfile:ro
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - gazella-net

  mongodb-setup:
    image: mongodb/mongodb-community-server:8.0.21-ubi8-slim
    container_name: mongodb_setup
    depends_on:
      - mongodb
    command: >
      bash -c "
      sleep 5;
      mongosh 'mongodb://${MONGO_ROOT}:${MONGO_ROOT_PASS}@mongodb:27017/?authSource=${MONGO_ROOT}' --eval 'rs.initiate({ _id: \"rs0\", members: [ { _id: 0, host: \"mongodb:27017\" } ] })'
      "
    networks:
      - gazella-net

  article-data-service:
    image: article-data-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: articles_data_service
    ports:
      - "6000:8080"
      - "6001:8081"
    networks:
      - gazella-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://${MONGO_USER}:${MONGO_USER_PASS}@mongodb:27017/${MONGO_DB}?replicaSet=rs0
      - MongoDbName=${MONGO_DB}
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  mongo_key_vol:

networks:
  gazella-net:
    external: true
